# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Home_UI(object):
    def setupUi(self, Home_UI):
        Home_UI.setObjectName("Home_UI")
        Home_UI.resize(694, 832)
        Home_UI.setAutoFillBackground(False)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Home_UI)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.TitleLabel = TitleLabel(Home_UI)
        self.TitleLabel.setObjectName("TitleLabel")
        self.verticalLayout.addWidget(self.TitleLabel)
        self.BodyLabel = BodyLabel(Home_UI)
        self.BodyLabel.setObjectName("BodyLabel")
        self.verticalLayout.addWidget(self.BodyLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.PixmapLabel = PixmapLabel(Home_UI)
        self.PixmapLabel.setPixmap(QtGui.QPixmap("adv.jpg"))
        self.PixmapLabel.setObjectName("PixmapLabel")
        self.horizontalLayout_2.addWidget(self.PixmapLabel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)

        self.retranslateUi(Home_UI)
        QtCore.QMetaObject.connectSlotsByName(Home_UI)

    def retranslateUi(self, Home_UI):
        _translate = QtCore.QCoreApplication.translate
        Home_UI.setWindowTitle(_translate("Home_UI", "Form"))
        self.TitleLabel.setText(_translate("Home_UI", "BlindWaterMask 图文盲水印"))
        self.BodyLabel.setText(_translate("Home_UI", "<html><head/><body><p><span style=\" font-size:8pt;\">软件开发：Duyuxuan</span></p><p><span style=\" font-size:8pt;\">此软件参考自开源项目：</span></p><p>guofei9987/text_blind_watermark<br/>guofei9987/blind_watermark</p></body></html>"))
from qfluentwidgets import BodyLabel, PixmapLabel, TitleLabel
