# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'img2_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Img2_UI(object):
    def setupUi(self, Img2_UI):
        Img2_UI.setObjectName("Img2_UI")
        Img2_UI.resize(762, 549)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Img2_UI)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(239, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.TitleLabel = TitleLabel(Img2_UI)
        self.TitleLabel.setObjectName("TitleLabel")
        self.verticalLayout.addWidget(self.TitleLabel)
        self.BodyLabel = BodyLabel(Img2_UI)
        self.BodyLabel.setObjectName("BodyLabel")
        self.verticalLayout.addWidget(self.BodyLabel)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.img2buuton = DropDownPushButton(Img2_UI)
        self.img2buuton.setObjectName("img2buuton")
        self.verticalLayout_2.addWidget(self.img2buuton)
        self.img2input1 = PushButton(Img2_UI)
        self.img2input1.setObjectName("img2input1")
        self.verticalLayout_2.addWidget(self.img2input1)
        self.img2input2_2 = PushButton(Img2_UI)
        self.img2input2_2.setObjectName("img2input2_2")
        self.verticalLayout_2.addWidget(self.img2input2_2)
        self.img2input3 = PushButton(Img2_UI)
        self.img2input3.setObjectName("img2input3")
        self.verticalLayout_2.addWidget(self.img2input3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Label01 = CaptionLabel(Img2_UI)
        self.Label01.setObjectName("Label01")
        self.horizontalLayout_2.addWidget(self.Label01)
        self.img2pwd = LineEdit(Img2_UI)
        self.img2pwd.setObjectName("img2pwd")
        self.horizontalLayout_2.addWidget(self.img2pwd)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.CaptionLabel = CaptionLabel(Img2_UI)
        self.CaptionLabel.setObjectName("CaptionLabel")
        self.horizontalLayout_3.addWidget(self.CaptionLabel)
        self.img2shape = LineEdit(Img2_UI)
        self.img2shape.setObjectName("img2shape")
        self.horizontalLayout_3.addWidget(self.img2shape)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)

        self.retranslateUi(Img2_UI)
        QtCore.QMetaObject.connectSlotsByName(Img2_UI)

    def retranslateUi(self, Img2_UI):
        _translate = QtCore.QCoreApplication.translate
        Img2_UI.setWindowTitle(_translate("Img2_UI", "Form"))
        self.TitleLabel.setText(_translate("Img2_UI", "图片盲水印 图片"))
        self.BodyLabel.setText(_translate("Img2_UI", "<html><head/><body><p><span style=\" font-size:8pt;\">在图片中嵌入图片</span></p><p><span style=\" font-size:8pt;\">需要水印图片小于30kb</span></p></body></html>"))
        self.img2buuton.setText(_translate("Img2_UI", "添加图片/提取图片"))
        self.img2input1.setText(_translate("Img2_UI", "选择要操作的图片"))
        self.img2input2_2.setText(_translate("Img2_UI", "选择要作为水印的图片"))
        self.img2input3.setText(_translate("Img2_UI", "选择图片的保存路径"))
        self.Label01.setText(_translate("Img2_UI", "密码"))
        self.CaptionLabel.setText(_translate("Img2_UI", "wm_shape"))
from qfluentwidgets import BodyLabel, CaptionLabel, DropDownPushButton, LineEdit, PushButton, TitleLabel
