# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'img_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Img_UI(object):
    def setupUi(self, Img_UI):
        Img_UI.setObjectName("Img_UI")
        Img_UI.resize(746, 389)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Img_UI)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(256, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.TitleLabel = TitleLabel(Img_UI)
        self.TitleLabel.setObjectName("TitleLabel")
        self.verticalLayout.addWidget(self.TitleLabel)
        self.BodyLabel = BodyLabel(Img_UI)
        self.BodyLabel.setObjectName("BodyLabel")
        self.verticalLayout.addWidget(self.BodyLabel)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.imgbutton = DropDownPushButton(Img_UI)
        self.imgbutton.setObjectName("imgbutton")
        self.verticalLayout_2.addWidget(self.imgbutton)
        self.imginput1 = PushButton(Img_UI)
        self.imginput1.setObjectName("imginput1")
        self.verticalLayout_2.addWidget(self.imginput1)
        self.imginput2 = PushButton(Img_UI)
        self.imginput2.setObjectName("imginput2")
        self.verticalLayout_2.addWidget(self.imginput2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.CaptionLabel_3 = CaptionLabel(Img_UI)
        self.CaptionLabel_3.setObjectName("CaptionLabel_3")
        self.horizontalLayout_4.addWidget(self.CaptionLabel_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4.addLayout(self.horizontalLayout_5)
        self.imgpwd = LineEdit(Img_UI)
        self.imgpwd.setObjectName("imgpwd")
        self.horizontalLayout_4.addWidget(self.imgpwd)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.CaptionLabel = CaptionLabel(Img_UI)
        self.CaptionLabel.setObjectName("CaptionLabel")
        self.horizontalLayout_2.addWidget(self.CaptionLabel)
        self.imgwm = LineEdit(Img_UI)
        self.imgwm.setObjectName("imgwm")
        self.horizontalLayout_2.addWidget(self.imgwm)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.CaptionLabel_2 = CaptionLabel(Img_UI)
        self.CaptionLabel_2.setObjectName("CaptionLabel_2")
        self.horizontalLayout_3.addWidget(self.CaptionLabel_2)
        self.imgshape = LineEdit(Img_UI)
        self.imgshape.setObjectName("imgshape")
        self.horizontalLayout_3.addWidget(self.imgshape)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(257, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)

        self.retranslateUi(Img_UI)
        QtCore.QMetaObject.connectSlotsByName(Img_UI)

    def retranslateUi(self, Img_UI):
        _translate = QtCore.QCoreApplication.translate
        Img_UI.setWindowTitle(_translate("Img_UI", "Form"))
        self.TitleLabel.setText(_translate("Img_UI", "图片盲水印 文本"))
        self.BodyLabel.setText(_translate("Img_UI", "<html><head/><body><p>在图片中嵌入不可见的文本</p></body></html>"))
        self.imgbutton.setText(_translate("Img_UI", "添加水印/提取水印"))
        self.imginput1.setText(_translate("Img_UI", "选择要操作的图片"))
        self.imginput2.setText(_translate("Img_UI", "选择图片的保存路径"))
        self.CaptionLabel_3.setText(_translate("Img_UI", "密码"))
        self.CaptionLabel.setText(_translate("Img_UI", "文字水印"))
        self.CaptionLabel_2.setText(_translate("Img_UI", "wm_shape"))
from qfluentwidgets import BodyLabel, CaptionLabel, DropDownPushButton, LineEdit, PushButton, TitleLabel
