# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imgresize_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ui_Resize_UI(object):
    def setupUi(self, Ui_Resize_UI):
        Ui_Resize_UI.setObjectName("Ui_Resize_UI")
        Ui_Resize_UI.resize(400, 457)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Ui_Resize_UI)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(46, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.TitleLabel = TitleLabel(Ui_Resize_UI)
        self.TitleLabel.setObjectName("TitleLabel")
        self.verticalLayout.addWidget(self.TitleLabel)
        self.BodyLabel = BodyLabel(Ui_Resize_UI)
        self.BodyLabel.setObjectName("BodyLabel")
        self.verticalLayout.addWidget(self.BodyLabel)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.resizebutton = PushButton(Ui_Resize_UI)
        self.resizebutton.setObjectName("resizebutton")
        self.verticalLayout_2.addWidget(self.resizebutton)
        self.resizein = PushButton(Ui_Resize_UI)
        self.resizein.setObjectName("resizein")
        self.verticalLayout_2.addWidget(self.resizein)
        self.resizeout = PushButton(Ui_Resize_UI)
        self.resizeout.setObjectName("resizeout")
        self.verticalLayout_2.addWidget(self.resizeout)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(47, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)

        self.retranslateUi(Ui_Resize_UI)
        QtCore.QMetaObject.connectSlotsByName(Ui_Resize_UI)

    def retranslateUi(self, Ui_Resize_UI):
        _translate = QtCore.QCoreApplication.translate
        Ui_Resize_UI.setWindowTitle(_translate("Ui_Resize_UI", "Form"))
        self.TitleLabel.setText(_translate("Ui_Resize_UI", "图片压缩"))
        self.BodyLabel.setText(_translate("Ui_Resize_UI", "<html><head/><body><p><span style=\" font-size:8pt;\">由于&quot;图片盲水印 图片&quot;需要水印图片小于30kb</span></p><p><span style=\" font-size:8pt;\">可以使用此工具进行一键压缩</span></p></body></html>"))
        self.resizebutton.setText(_translate("Ui_Resize_UI", "一键压缩"))
        self.resizein.setText(_translate("Ui_Resize_UI", "选择要操作的图片"))
        self.resizeout.setText(_translate("Ui_Resize_UI", "选择图片的保存路径"))
from qfluentwidgets import BodyLabel, PushButton, TitleLabel
