# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'v2text_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_V2text_UI(object):
    def setupUi(self, V2text_UI):
        V2text_UI.setObjectName("V2text_UI")
        V2text_UI.resize(409, 468)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(V2text_UI.sizePolicy().hasHeightForWidth())
        V2text_UI.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(V2text_UI)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.TitleLabel = TitleLabel(V2text_UI)
        self.TitleLabel.setObjectName("TitleLabel")
        self.verticalLayout.addWidget(self.TitleLabel)
        self.BodyLabel = BodyLabel(V2text_UI)
        self.BodyLabel.setObjectName("BodyLabel")
        self.verticalLayout.addWidget(self.BodyLabel)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.v2button = DropDownPushButton(V2text_UI)
        self.v2button.setObjectName("v2button")
        self.verticalLayout_2.addWidget(self.v2button)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.CaptionLabel_3 = CaptionLabel(V2text_UI)
        self.CaptionLabel_3.setObjectName("CaptionLabel_3")
        self.horizontalLayout_4.addWidget(self.CaptionLabel_3)
        self.v2pwd = LineEdit(V2text_UI)
        self.v2pwd.setObjectName("v2pwd")
        self.horizontalLayout_4.addWidget(self.v2pwd)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.CaptionLabel = CaptionLabel(V2text_UI)
        self.CaptionLabel.setObjectName("CaptionLabel")
        self.horizontalLayout_2.addWidget(self.CaptionLabel)
        self.v2wm = LineEdit(V2text_UI)
        self.v2wm.setObjectName("v2wm")
        self.horizontalLayout_2.addWidget(self.v2wm)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.CaptionLabel_2 = CaptionLabel(V2text_UI)
        self.CaptionLabel_2.setObjectName("CaptionLabel_2")
        self.horizontalLayout_3.addWidget(self.CaptionLabel_2)
        self.v2text = TextEdit(V2text_UI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.v2text.sizePolicy().hasHeightForWidth())
        self.v2text.setSizePolicy(sizePolicy)
        self.v2text.setObjectName("v2text")
        self.horizontalLayout_3.addWidget(self.v2text)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)

        self.retranslateUi(V2text_UI)
        QtCore.QMetaObject.connectSlotsByName(V2text_UI)

    def retranslateUi(self, V2text_UI):
        _translate = QtCore.QCoreApplication.translate
        V2text_UI.setWindowTitle(_translate("V2text_UI", "Form"))
        self.TitleLabel.setText(_translate("V2text_UI", "文字盲水印 V2"))
        self.BodyLabel.setText(_translate("V2text_UI", "<html><head/><body><p>把密文嵌入到明文中</p></body></html>"))
        self.v2button.setText(_translate("V2text_UI", "加密/解密"))
        self.CaptionLabel_3.setText(_translate("V2text_UI", "密码"))
        self.CaptionLabel.setText(_translate("V2text_UI", "密文"))
        self.CaptionLabel_2.setText(_translate("V2text_UI", "<html><head/><body><p align=\"center\"><span style=\" font-size:7pt;\">明文</span></p></body></html>"))
from qfluentwidgets import BodyLabel, CaptionLabel, DropDownPushButton, LineEdit, TextEdit, TitleLabel
